### ISSUE TITLE
On windows..

### ISSUE THREAD

**Issue by BenkaTv** [nicka/coinboss#18]
When i try to deploy 

$ source .env.$STAGE && sls deploy --verbose
'source' is not recognized as an internal or external command,
operable program or batch file.

**Comment by BenkaTv** [comment]
yarn run deploy
yarn run v1.3.2
$ source .env.$STAGE && sls deploy --verbose
'source' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by nicka** [comment]
🙈

**Comment by BenkaTv** [comment]
Why close?
