### ISSUE TITLE
document minimum Coinbase API key permissions

### ISSUE THREAD

**Issue by lukasnagl** [nicka/coinboss#5]
Coinbase offers to restrict the API key permissions to the ones really necessary. It would be nice if coinboss’ necessary permissions were documented. I would have guessed them to be:

* `wallet:buys:create`
* `wallet:payment-methods:read`
* `wallet:sells:create`
* `wallet:buys:create`

Is this correct?

**Comment by nicka** [comment]
Good point!

The required permissions are:
- wallet:accounts:read
- wallet:buys:create
- wallet:payment-methods:read
- wallet:sells:create
